export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FEATURED_PROPERTIES_SUCCESS = "FEATURED_PROPERTIES_SUCCESS";
export const FEATURED_PROPERTIES_FAIL = "FEATURED_PROPERTIES_FAIL";

export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const ADD_PROPERTY_FAIL = "ADD_PROPERTY_FAIL";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const  GET_PROPERTY_SUCCESS= " GET_PROPERTY_SUCCESS";
export const  GET_PROPERTY_FAIL= " GET_PROPERTY_FAIL";

export const SEARCH_PROPERTIES_SUCCESS= "SEARCH_PROPERTIES_SUCCESS";
export const SEARCH_PROPERTIES_FAIL= "SEARCH_PROPERTIES_FAIL";

export const ADD_COMMENT_SUCCESS= "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL= "ADD_COMMENT_FAIL";

export const GET_COMMENTS_SUCCESS= "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL= "GET_COMMENTS_FAIL";

export const GET_AGENTPROPERTY_SUCCESS= "GET_AGENTPROPERTY_SUCCESS";
export const GET_AGENTPROPERTY_FAIL= "GET_AGENTPROPERTY_FAIL";